### ISSUE TITLE
Possible Incompatibility with Prepare Carefully

### ISSUE THREAD

**Issue by Amnesiac9** [FluffierThanThou/WorkTab#100]
Upon starting a game, I added Map Reroll to my mod list, and started getting a huge amount of errors as shown in this screenshot: https://i.imgur.com/duiRnEC.png

The errors say something about work tab, so I wanted to report it here on the off chance you can understand what's happening and maybe find out why.

Only happens when I load the game.

**Comment by Amnesiac9** [comment]
Modlist that I was using ** before** adding Map Reroll and starting a new game:

<modNames>
			<li>Core</li>
			<li>HugsLib</li>
			<li>EdB Prepare Carefully</li>
			<li>Allow Tool</li>
			<li>Animal Tab</li>
			<li>Medical Tab</li>
			<li>Relations Tab</li>
			<li>Work Tab</li>
			<li>Blueprints</li>
			<li>Research Tree</li>
			<li>Colony Manager</li>
			<li>Dubs Mint Menus</li>
			<li>Fluffy Breakdowns</li>
			<li>ExtendedInspectData [B19]</li>
			<li>Hand Me That Brick Lite</li>
			<li>Pick Up And Haul</li>
			<li>Dismiss Trader</li>
			<li>P-Music</li>
			<li>VGP Vegetable Garden</li>
			<li>VGP_CoffeeTeaDrugs</li>
			<li>VGP Garden Medicine</li>
			<li>Heat Map</li>
			<li>RT Fuse</li>
			<li>Wandering Caravans [v2.3.5]</li>
			<li>[KV] Show Hair With Hats or Hide All Hats - B19</li>
			<li>ED-Embrasures</li>
			<li>[B19] Wild Animal Sex V3.2</li>
			<li>VGP Garden Tools</li>
			<li>Room Food</li>
			<li>[KV] RimFridge - B19</li>
			<li>PowerSwitch</li>
			<li>Animals Logic</li>
			<li>Stack XXL</li>
		</modNames>

**Comment by Amnesiac9** [comment]
Ok, I was wrong, the incompatibility is with Prepare Carefully! 

https://github.com/edbmods/EdBPrepareCarefully/issues/241

**Comment by Amnesiac9** [comment]
Here's a copy and paste of my issue report on Prepare Carefully.

Hello,

So I've been getting errors with my mods and did a TON of testing, and I've found an incompatibility with Fluffy's Work Tab and Prepare Carefully.

After starting a game with only 3 mods, then upon SAVING and Loading the game thereafter, I receive this error log:  https://git.io/fA1o1

Pic of the error: https://i.imgur.com/sKzspwF.png

### The Mod List:

- Core
- HugsLib
- EdB Prepare Carefully
- Work Tab

### Some info from testing:

- When I do not choose "prepare carefully" at the start, the errors **Do Not** happen after saving then loading the game.

- If I remove WorkTab, but choose prepare carefully, the errors **Do Not** happen.

- If I add WorkTab AFTER starting and saving a game with Prepare Carefully, the errors **Do Not** happen.

The Errors DO happen when I:

Start a new game, choose prepare carefully with 3 colonists, change no settings at all, save game, quit to main menu, load game. Each time I load, the errors happen.

Hopefully this helps!!

**Comment by FluffierThanThou** [comment]
Hey,

Thanks for the extensive report, and all the work you've put into it. I'm sorry it took me so long to reply, life got in the way.

The warnings and errors you're seeing are - as far as I understand it - a result of Prepare Carefully generating pawns, but never disposing of them correctly. When the pawns are generated, their work settings are generated too, which triggers Work Tab to create and store their priorities. When it comes to actually saving these priorities, Work Tab checks to see if the pawns they belong to have been destroyed, or otherwise disposed of. Since Prepare Carefully doesn't mark them as destroyed, Work Tab saves a reference to them, but these 'ghost' pawns are themselves never actually saved by the game. When the game tries to load the priorities, it fails to find the referenced pawns, and gives a bunch of errors. 

The good news is that these errors are harmless, and they will only occur once. The bad news is that there's not much that I can do, there's not really any good way for me to check if a pawn exists other than trusting what that pawn tells me.
