### ISSUE TITLE
Expose default numeric priority as an option

### ISSUE THREAD

**Issue by frenchiveruti** [FluffierThanThou/WorkTab#31]
That way we don't have to manually ser every single character to a low level of "priority" for each job type.
Maybe a "config" option so the user can choose?

**Comment by FluffierThanThou** [comment]
I'll look into making this an option

**Comment by FluffierThanThou** [comment]
I have to admit I don't particularly see the point of this one.

Another slight issue is that these 'defaults' are currently drawn from the vanilla priorities, which reliefs me from having to duplicate a bunch of logic to decide which and how many jobs should be on for new pawns. Only when vanilla doesn't have a value (which _only_ happens when you've added jobs/workgivers in an existing save game) do I use a real default value, which is 0.

**Comment by frenchiveruti** [comment]
Thanks fluffy for explaining it.  greets
