### ISSUE TITLE
What happens to priorities when a pawn is (temporarily) medically incapable of doing a task?

### ISSUE THREAD

**Issue by FluffierThanThou** [FluffierThanThou/WorkTab#44]
Also, apparently it spams errors when a pawn loses capability to do something.

**Comment by MrWeeGee** [comment]
Could be what you're referring to. Getting related errors on a new colony with WT 1.9, where it complains about colonists completely incapable of performing bills due to backstory:

> Found priority 1 for a pawn incapable of DoBillsSculpt. Did you add/change mods without starting a new game?
Verse.Log:Error(String)
Fluffy_Tabs.PawnPrioritiesTracker:GetPriority(WorkGiverDef, Int32)
Fluffy_Tabs.PawnPrioritiesTracker:GetPriority(WorkGiverDef)
Fluffy_Tabs.<>c__DisplayClass9_0:<_CacheWorkGiversInOrder>b__1(WorkGiver)
System.Linq.<CreateWhereIterator>c__Iterator1D`1:MoveNext()
System.Collections.Generic.List`1:AddEnumerable(IEnumerable`1)
System.Collections.Generic.List`1:.ctor(IEnumerable`1)
System.Linq.Enumerable:ToArray(IEnumerable`1)
System.Linq.QuickSort`1:.ctor(IEnumerable`1, SortContext`1)
System.Linq.<Sort>c__Iterator21:MoveNext()
System.Collections.Generic.List`1:AddEnumerable(IEnumerable`1)
System.Collections.Generic.List`1:.ctor(IEnumerable`1)
System.Linq.Enumerable:ToList(IEnumerable`1)
Fluffy_Tabs.Detours_WorkSettings:_CacheWorkGiversInOrder()
RimWorld.Pawn_WorkSettings:get_WorkGiversInOrderEmergency()
RimWorld.JobGiver_Work:TryGiveJob(Pawn)
Combat_Realism.Detours_ThinkNode_JobGiver:TryIssueJobPackage(Pawn)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn)
RimWorld.ThinkNode_Conditional:TryIssueJobPackage(Pawn)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn)
Verse.AI.Pawn_JobTracker:DetermineNextJob(ThinkTreeDef&)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:EndCurrentJob(JobCondition, Boolean)
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()

Errors disappear when I roll back to 1.7, nor do I have any using 1.9 on an existing 1.7 save. At least until more colonists show up, perhaps.

**Comment by FluffierThanThou** [comment]
It spams errors, that's what happens.

**Comment by maarxx** [comment]
Yeah, same, got spammed with error when my Handler lost his Jaw in combat:

Found priority 9 for a pawn incapable of Tame. Did you add/change mods without starting a new game?
Verse.Log:Error(String)
Fluffy_Tabs.PawnPrioritiesTracker:GetPriority(WorkGiverDef, Int32)
Fluffy_Tabs.PawnPrioritiesTracker:GetSaveString()
Fluffy_Tabs.PawnPrioritiesTracker:ExposeData()
Verse.Scribe_Deep:LookDeep(PawnPrioritiesTracker&, Boolean, String, Object[])
Verse.Scribe_Collections:LookList(List`1&, Boolean, String, LookMode, Object[])
Verse.Scribe_Collections:LookList(List`1&, String, LookMode, Object[])
Fluffy_Tabs.WorldObject_Priorities:ExposeData()
Verse.Scribe_Deep:LookDeep(WorldObject&, Boolean, String, Object[])
Verse.Scribe_Collections:LookList(List`1&, Boolean, String, LookMode, Object[])
Verse.Scribe_Collections:LookList(List`1&, String, LookMode, Object[])
RimWorld.Planet.WorldObjectsHolder:ExposeData()
Verse.Scribe_Deep:LookDeep(WorldObjectsHolder&, Boolean, String, Object[])
Verse.Scribe_Deep:LookDeep(WorldObjectsHolder&, String, Object[])
RimWorld.Planet.World:ExposeComponents()
RimWorld.Planet.World:ExposeData()
Verse.Scribe_Deep:LookDeep(World&, Boolean, String, Object[])
Verse.Scribe_Deep:LookDeep(World&, String, Object[])
Verse.Game:ExposeData()
Verse.Scribe_Deep:LookDeep(Game&, Boolean, String, Object[])
Verse.Scribe_Deep:LookDeep(Game&, String, Object[])
Verse.GameDataSaveLoader:<SaveGame>m__A1B()
Verse.SafeSaver:DoSave(String, String, Action)
Verse.SafeSaver:Save(String, String, Action)
Verse.GameDataSaveLoader:SaveGame(String)
RimWorld.<DoFileInteraction>c__AnonStorey380:<>m__4B2()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&)
Verse.LongEventHandler:LongEventsUpdate(Boolean&)
Verse.Root:Update()
Verse.Root_Play:Update()

**Comment by FluffierThanThou** [comment]
I've completely rewritten the priority code for the A17 (pre-release) version, it should be much more robust now.
