### ISSUE TITLE
tried to enable work XXX for colonist, who is incapable of said work

### ISSUE THREAD

**Issue by EricChen1248** [FluffierThanThou/WorkTab#54]
The bug is persistent across saves. Manually deleted the the colonist through the debug menu, still appears. This colonist was not actually incapable of the work though. Manual enabling doesn't work either, in check mark, numbers, or DF mode. The colonist was recruited from an ancient danger if that helps.

[output_log.txt](https://github.com/FluffierThanThou/WorkTab/files/840676/output_log.txt)

tried to enable work Cleaning for Sparkles, who is incapable of said work.
Verse.Log:Error(String)
Fluffy_Tabs.PawnPrioritiesTracker:SetPriority(WorkGiverDef, Int32, Int32)
Fluffy_Tabs.PawnPrioritiesTracker:SetPriority(WorkTypeDef, Int32, Int32)
Fluffy_Tabs.PawnPrioritiesTracker:InitPriorityCache()
Fluffy_Tabs.PawnPrioritiesTracker:.ctor(Pawn)
Fluffy_Tabs.WorldObject_Priorities:WorkgiverTracker(Pawn)
Fluffy_Tabs.Widgets:Priorities(Pawn)
Fluffy_Tabs.Detours_WorkSettings:_SetPriority(WorkTypeDef, Int32)
RimWorld.Pawn_WorkSettings:Disable(WorkTypeDef)
Hospitality.Detouring.Pawn_WorkSettings:CheckForDisabledTypes(Pawn_WorkSettings, Pawn)
Hospitality.Detouring.Pawn_WorkSettings:ExposeData(Pawn_WorkSettings)
Verse.PostLoadInitter:DoAllPostLoadInits()
Verse.Game:LoadGame()
Verse.SavedGameLoader:LoadGameFromSaveFile(String)
Verse.Root_Play:<Start>m__736()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__733()

**Comment by EricChen1248** [comment]
I removed the colonist from the save file, and the error no longer occurs. Here is the section I removed.
[Sparkles.txt](https://github.com/FluffierThanThou/WorkTab/files/843760/Sparkles.txt)

**Comment by Valerate** [comment]
I currently have the same error, which is caused by a raider without a jaw, and fluffy tries to get him to do warding


tried to enable work Warden for Frost, who is incapable of said work.
Verse.Log:Error(String)
Fluffy_Tabs.PawnPrioritiesTracker:SetPriority(WorkGiverDef, Int32, Int32)
Fluffy_Tabs.PawnPrioritiesTracker:SetPriority(WorkGiverDef, Int32)
Fluffy_Tabs.PawnPrioritiesTracker:SetPriority(WorkTypeDef, Int32)
Fluffy_Tabs.Detours_WorkSettings:_SetPriority(WorkTypeDef, Int32)
RimWorld.Pawn_WorkSettings:EnableAndInitialize()
RimWorld.LordToil_Siege:SetAsBuilder(Pawn)
RimWorld.LordToil_Siege:UpdateAllDuties()
RimWorld.LordToil_Siege:LordToilTick()
Verse.AI.Group.Lord:LordTick()
Verse.AI.Group.LordManager:LordManagerTick()
Verse.Map:MapPostTick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()

**Comment by FluffierThanThou** [comment]
I've completely rewritten the priority code for the A17 (pre-release) version, it should be much more robust now.
