### ISSUE TITLE
Display for timed priorities

### ISSUE THREAD

**Issue by schoos76** [FluffierThanThou/WorkTab#65]
Prison Architect uses a nice display for time dependant settings. Would it be possible to implement something like this here as well?

just to be sure what I'm talking about: Instead of selecting the time range in the "time widget" at the bottom and then in the priority box assigning a different priority, I suggest to assign the priorities directly in the "time widget", e.g, where there would be e.g. these numbers:
 3 3 3 3 3 3 1 1 3 3 3 3 3 3 3 3 3 3 2 2 3 3 3 3, meaning: for 0 to 6, do this task with prio 3, then for two hours prio 1, then throughout the day until 6 pm prio 3 again, between 6 and 8 with prio two and then 3 again till midnight.

I think management would be easier this way.

**Comment by FluffierThanThou** [comment]
good idea, and I'm vaguely familiar with the PA way of doing this (haven't played it in a while).

I'm however not sure how well this would work in a much more cluttered interface (more pawns * more jobs * more options = much more clutter). Putting it on the 'maybe later' pile.

**Comment by schoos76** [comment]
Ah, I see your concerns here. Maybe something with a "ctrl+left click" that moves the 24h priority settings of one task and one pawn to the time widget, where it can be edited/viewed?

**Comment by MyrddinE** [comment]
Note that the UI that Prison Architect uses only allows for one task at a time. Cell block A is showering, Cell block B is eating, and it doesn't matter if someone in Cell block B is not hungry... they are eating, and that's the only task they can do during that time period.

This would be like only letting a settler in Rimworld to have one task, at priority 1, and that's it for an entire hour. No other tasks, no other priorities.

While there might be occasional times when that's how you want to schedule your pawns, it's an outlier. You don't want someone standing in the kitchen doing nothing just because it's time to cook, even if the larder is full. It's inefficient; a prison doesn't care much about how inefficient the prisoner's time is, but on the frontier when there's only three of us to build a settlement and try not to die? That's crazy.

I don't think a UI that emulates PA will do a good job of allowing the complex scheduling requirements that Rimworld needs. Now I'm not saying there couldn't be a different UI that does a better job than the current one. There are certainly possible ways to make timed scheduling more clear. How about:

> Alt-click on a task and that task expands to fill the UI. Each row is still one colonist. But instead of each column being a different task, the columns become the hours. You can change the priority of that one task on an hourly basis. A button at the top returns you to the normal UI where you see all the tasks.

Or how about this:

> Add a button that changes Fluffy's clock at the bottom into a list of tasks (while changing the columns into hours), so you could navigate from task to task, and even highlight multiple tasks, in a similar way to how you navigate from hour to hour in the current UI. Clicking the button would swap it back to how it is now.

Both suggestions suggestion combines pawns, hours, and priority for a single task, in contrast to the current scheduling UI that combines pawns, tasks, and priority for a single hour (or set of hours). By swapping the hours and tasks you do allow easier access to a different kind of scheduling. But it's a lot of work, and it doesn't let you do anything you can't already do. I don't think it really _simplifies_ anything, it just makes certain kinds of scheduling easier.

I would certainly make use of the feature, if it were added, but I'm not sure it's really worth the work.

**Comment by FluffierThanThou** [comment]
I've long been toying with gnomoria style work assignments. Note that I haven't played that game in ages, but from what I remember, gnomoria had certain 'profession' pre-sets, that included a number of related jobs. The work types in RimWorld are similar, but unlike those of gnomoria, the user can not edit the work types, nor can a job appear in multiple types.

I'm thinking of a UI where work types and specific jobs can be assigned to 'professions' and priorities within the profession, and these professions can then be assigned to pawns with a certain priority. Professions could be saved (and exported), and each pawn could have one or more professions.

This would make the initial setup more complicated (I'd probably provide some defaults based on work types), but allow for quick and detailed assignment of priorities once set up. 

However, this would be a rather massive task, and break completely from the 'spreadsheet' style of work priorities we've all become accustomed to. I'd welcome your thoughts!

**Comment by FluffierThanThou** [comment]
Some further musings....

For the timed mode, I'm envisioning a form of gantt chart, which would actually be similar to the PA assignments. Allowing for overlapping professions (multiple professions in the same time slots) would allow the same flexibility that we have now.

This would all be possible because using professions instead of worktypes/jobs essentially removes one dimension. We would no longer need columns for worktypes, as professions could be identified with a label/color/icon.

**Comment by chaos17** [comment]
Hi,

I just saw your thread and I tried to do something... I kept as much as I could what already exist in the game, so here the first "draft" 
![worktab](https://user-images.githubusercontent.com/6094831/39788828-8d62cb58-532c-11e8-8caf-2a4a78ccc2f3.png)

The picture feature a condensed main menu for professions that player will be able 
- to name himself. He can > add > rename > delete
- Options tab feature shortcuts to: worktab (re-organized) > Schedule (will use Restrict menu features) > Assign.
- Workers: list of assigned pawn for that profession.

For now I only worked on the wortab "presentation". If you like it I can continue to work on the other options.

Take care and thank you for your hard work.
